name: Generate Provenance BZL

on:
  workflow_dispatch:
  
jobs:
  generate-attestation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: pip install sigstore
    - run: sigstore attest --predicate MODULE.bazel.predicate --predicate-type "https://slsa.dev/provenance/v1" MODULE.bazel
