

name: Generate Provenance Multi Star

on:
  workflow_dispatch:
  
jobs:
  generate-attestation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: './*.txt'
